auto: true
markdown: rdiscount
pygments: true

title: Abstract AST

url: http://mouk.github.io

permalink: /:year/:month/:title/

author:
    name: Moukarram Kabbash
    email: webmaster@abstractast.com
    github: mouk
    twitter: dermouk
    gravatar: http://www.gravatar.com/avatar/dd2dbc41e3babec00f70d4becf4092cf?s=160

comments:
    provider: disqus
    disqus:
        short_name: abstractast
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-10348417-1'
        domain: 'bstractast.com'