auto: true
markdown: rdiscount
pygments: true

title: Abstract AST

url: http://abstractast.com

permalink: /:year/:month/:day/:title/

author:
    name: Moukarram Kabbash
    email: webmaster@abstractast.com
    github: mouk
    twitter: dermouk
#    gravatar: http://www.gravatar.com/avatar/5b7d3122776b44cfb18ed7aa865804a1.png

comments:
    provider: disqus
    disqus:
        short_name: abstractast
        
analytics:
    provider: google 
    google: 
        tracking_id: 'UA-10348417-1'
        domain: 'bstractast.com'